name: Build and Deploy Docs

on: 
  workflow_dispatch:
  schedule:
    - cron:  "0 4 10 * *"


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install deps
        run: |
          sudo apt-get update && sudo apt-get install -y git doxygen graphviz
          sudo mkdir /docs && sudo chmod 777 /docs
          git clone https://github.com/jothepro/doxygen-awesome-css --depth=1

      - name: gen docs
        run: chmod +x docs.sh && ./docs.sh

      - name: disable indexation
        run: cp robots.txt /docs/html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: /docs/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
